### ISSUE TITLE
Errors when using negations in interface calls

### ISSUE THREAD

**Issue by pebenito** [SELinuxProject/selint#244]
```
kernel.if:         [16](https://github.com/SELinuxProject/refpolicy/actions/runs/3053849671/jobs/4924997080#step:7:17)73: (F): syntax error, unexpected DASH (F-001)
 1673 |     init_write_mountpoint_files($1, -proc_type)
      |                                     ^
kernel.if:         1673: (F): Error: Invalid statement (F-001)
 1673 |     init_write_mountpoint_files($1, -proc_type)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: Failed to parse files
```
https://github.com/SELinuxProject/refpolicy/actions/runs/3053849671/jobs/4924997080#step:7:18

**Comment by cgzones** [comment]
Should be fixed by https://github.com/SELinuxProject/selint/commit/41a575e82dea5cd7f60b4fa7aeb84405dba3baba

**Comment by dburgener** [comment]
Thanks for the report, @pebenito and the diagnosis @cgzones.  I guess we need a new release to include that commit.  Probably v1.3.0.  I can make a CHANGELOG update this weekend for that.  Christian, what's the path at that point to getting the release to refpolicy?  Does it need to make it into a debian release?

**Comment by dburgener** [comment]
#245

**Comment by cgzones** [comment]
The [CI of Refpolicy](https://github.com/SELinuxProject/refpolicy/blob/7d298ade4d57214f400ecd2d9e91f5074a47a5df/.github/workflows/tests.yml#L25-L28) uses the SELint version from Debian testing.
So it would require a new Debian release and a couple of days migration time from Debian unstable to testing.

**Comment by pebenito** [comment]
I'm open to a patch that will change refpolicy CI to build a selint tag, similar to how it does for the userspace.

**Comment by dburgener** [comment]
v1.3.0 is released now, so that is available as needed.  Currently Christian's PR to build selint in the refpolicy CI goes directly to the commit hash fixing it, so the release is no longer strictly necessary, but it is available.  Regardless, I think this is addressed from the selint side, so I'm going to close this issue and let the refpolicy PR run its course complete the resolution.
