### ISSUE TITLE
configuration error from source code

### ISSUE THREAD

**Issue by icegood** [SELinuxProject/selint#252]
While configuring from source in a ubuntu20-based docker environment, i obtained:
1) pkg-config is missing as dependency in documentation
2) even thought 'apt install check
Reading package lists... Done
Building dependency tree       
Reading state information... Done
check is already the newest version (0.10.0-3build2).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.'

i obtained from configure:

> checking for CHECK... no
configure: error: Check not found

it is good idea to migrate to cmake...

**Comment by icegood** [comment]
under  debian:bullseye
configuration goes i bit further:

`checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for check >= 0.11.0... yes
checking for library containing cfg_init... -lconfuse
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for inttypes.h... (cached) yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int8_t... yes
checking for size_t... (cached) yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for memset... yes
checking for strdup... yes
checking for help2man... no
./configure: line 5590: syntax error near unexpected token `drd,'
./configure: line 5590: `AX_VALGRIND_DFLT(drd, off)'
`
seems the same as in 
https://github.com/tpm2-software/tpm2-abrmd/issues/404

**Comment by dburgener** [comment]
The Ubuntu error is because the distro is shipping an older version of check.  You can add the --without-check flag to ./configure and it will skip the dependency and you won't be able to run unit tests.

The second issue looks like a missing autoconf-archive dependency.  See the "installing from git" section in the README.
