### ISSUE TITLE
New point release?

### ISSUE THREAD

**Issue by cgzones** [SELinuxProject/selint#259]
The Debian freeze window for Bookworm is approaching (2023-02-12).
The latest release is 4 month old and since them a couple of worthy fixes have landed:

* Warn on duplicate policy configuration files (https://github.com/SELinuxProject/selint/commit/75f68608d5a4a53ec5219dece1cabbe7b0aadd7e)
* Reduce recursion in free_policy_node (https://github.com/SELinuxProject/selint/commit/9e389c84accbf15aaaa772038d188ec71477dfd2)
* Support disable commands for tunable conditions (https://github.com/SELinuxProject/selint/commit/378357f276826ee0f4d0642f3ac26154dd8c5c02)
* Support ifn?def in .if files (https://github.com/SELinuxProject/selint/commit/211354e8ffc1a6fd7a7ada1fc266464685dc8dbb)

The only addition was `Add new check to warn about incorrect usage of audit_access permission` (https://github.com/SELinuxProject/selint/commit/e83ac2a42d05227fcd374bb2d9211df876db32d3), which is quite limited in scope and chances of regressions or false-positives are low.

**Comment by dburgener** [comment]
Thanks for the info on the Debian freeze and the analysis of the history.  My only concern here is that we haven't added a check in a point release before.  I agree that the check is unlikely to introduce regressions or false positives.  The question in my mind is whether it will cause user annoyance if we signal new findings on their source in a point release.  As a user of clippy (rust linter) in another project, my CI regularly breaks unexpectedly when they add new checks and my CI automatically grabs the latest version of clippy.

You're probably right that a point release makes sense anyways.  Let me think about it for a day or two.

**Comment by dburgener** [comment]
Okay, thought about this and discussed it a bit, and I think Semantic Versioning is pretty clear here.  We added backwards compatible functionality (a new check), so we should call this 1.4, even though the functional change is pretty small.  Unless you object, I think we should make a new release this week and call it 1.4.

**Comment by cgzones** [comment]
Sound good to me :+1:

**Comment by dburgener** [comment]
https://github.com/SELinuxProject/selint/pull/261

Would appreciate it if you have time to give everything a once over today and I'll make the release in a few hours.

**Comment by dburgener** [comment]
1.4.0 released
